### ISSUE TITLE
Question - Why Testerra2 for Windows Automation

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra-skeleton#3]
First of: Happy new year!

These are two questions in one:

1.) Can you add a question type to the issues. Or, where would you like such questions go? They are neither a bug nor a feature, sec val.

2.) in another Issues @mreiche mentioned that Testerra2 would be suitable for Windows automation:

"Its not official supported yet, but already in use in various projects requiring Windows automation. I recommend to checkout the testerra2 branch of the skeleton repo" <-- this repo

Why is Testerra2 better for Windows automation?

Thank you.
Kind regards.
Christian

**Comment by mreiche** [comment]
1. The question label already exists.
2. The internal infrastructure in Testerra 2 is much more lighweight, faster and way cleaner according to `WebDriver` and `WebDriverFactory` interfaces to implement a strict WebDriver lifecycle controlled by `WebDriverRequest` to support other types of WebDrivers like `WinAppDriver`.

Testerra1 controls how sessions are handled globally by properties, but that doesn't fit the requirements for applications under test using WinAppDriver, because we won't close applications for reasons, after a test has finished. In Testerra 2, we can control the handling of a session per request (see here: https://github.com/telekom/testerra/blob/testerra2/core/src/main/java/eu/tsystems/mms/tic/testframework/webdrivermanager/WebDriverRequest.java)

Another aspect is, that focusing on the WebDriver interface, we were able to abstract a lot of features for `UiElement` in the core so the codebase of extensions is way smaller.
  * Testerra 1: https://github.com/telekom/testerra-appium-connector/blob/master/appium/src/main/java/eu/tsystems/mms/tic/testframework/mobile/guielement/AppiumGuiElementCoreAdapter.java
  * Testerra 2: https://github.com/telekom/testerra-appium-connector/blob/testerra2/appium/src/main/java/eu/tsystems/mms/tic/testframework/mobile/guielement/AppiumGuiElementCoreAdapter.java
